export const CAP= "CAP";
export const SELECTCURRENCY="SELECTCURRENCY";
export const ISMARKETLOADING="ISMARKETLOADING";
export const CHANGETHEME="CHANGETHEME";
export const SEARCHCHANGE="SEARCHCHANGE";
export const PORTFOLIOSTATUS = "PORTFOLIOSTATUS";
export const PORTFOLIOUPDATE = "PORTFOLIOUPDATE";